# Copyright 2026 Admenri.
# Use of this source code is governed by a MIT-style license that can be
# found in the LICENSE file.

# Embeds a SPIR-V binary as a C++ header with a word array.
#
# Usage: cmake -DSPIRV_BIN=... -DHEADER_OUT=... -DVAR_NAME=... -P embed_spirv.cmake
if (NOT EXISTS "${SPIRV_BIN}")
  message(FATAL_ERROR "SPIR-V input not found: ${SPIRV_BIN}")
endif ()

file(READ "${SPIRV_BIN}" hex HEX)
string(LENGTH "${hex}" hex_length)
set(words "")
set(i 0)
# SPIR-V is little-endian: bytes b0 b1 b2 b3 form the word 0xb3b2b1b0.
while (i LESS hex_length)
  string(SUBSTRING "${hex}" ${i} 8 bytes)
  string(SUBSTRING "${bytes}" 6 2 b0)
  string(SUBSTRING "${bytes}" 4 2 b1)
  string(SUBSTRING "${bytes}" 2 2 b2)
  string(SUBSTRING "${bytes}" 0 2 b3)
  string(APPEND words "0x${b0}${b1}${b2}${b3},")
  math(EXPR i "${i} + 8")
endwhile ()

file(WRITE "${HEADER_OUT}"
  "// Generated by embed_spirv.cmake. DO NOT EDIT.\n"
  "#pragma once\n"
  "#include <cstddef>\n"
  "#include <cstdint>\n"
  "static const uint32_t ${VAR_NAME}[] = {${words}};\n"
  "static const size_t ${VAR_NAME}Size = sizeof(${VAR_NAME}) / sizeof(uint32_t);\n"
)
